apiVersion: apps/v1
kind: Deployment
metadata:
  name: easyhtml
  labels:
    version: v1

spec:
  selector:
    matchLabels:
      app: easyhtml
  replicas: 2
#spec:
#  restartPolicy: Always
  template:
    metadata:
      labels:
        app: easyhtml
    spec:
      containers:
      - name: easyhtml
        image: jansora/easyhtml:v1
        imagePullPolicy: Never
        command: ['sh']
        args: ["service nginx start && java -Xms128M -Xmx128M -jar easyhtml.jar"]
        workingDir: /app
        env:
        - name: str
          value: "/etc/run.sh"

        ports:
        - containerPort: 80
          name: nginx
          protocol: TCP
        volumeMounts:
        - name: tmp #挂载设备的名字，与volumes[*].name 需要对应
          mountPath: /app/tmp #挂载到容器的某个路径下
          readOnly: False
      volumes: #定义一组挂载设备
        - name: tmp #定义一个挂载设备的名字
          hostPath:
            path: /Users/jansora/tmp #挂载设备类型为hostPath，路径为宿主机下的/opt,这里设备类型支持很多种
